.TH tntnet\-config 1 "2006\-07\-23" Tntnet "Tntnet users guide"
.SH NAME
.PP
tntnet\-config \- output compiler flags for 
.BR tntnet (8) 
usage
.SH SYNOPSIS
.PP
\fB\fCtntnet-config\fR [\fB\fC--libs\fR] [\fB\fC--cxxflags\fR] [\fB\fC--config\fR[=\fIapp\fP]] [\fB\fC--makefile\fR[=\fIapp\fP]] [\fB\fC--project\fR=\fIapp\fP] [\fB\fC--auto-project\fR=\fIapp\fP] [\fB\fC--help\fR] [\fB\fC--version\fR]
.SH DESCRIPTION
.PP
This manual page documents briefly the tntnet\-config command.
.SH OPTIONS
.PP
This program's options start with two dashes ('\-'). A summary of options is
included below.
.TP
\fB\fC--libs\fR
Output linker flags.
.TP
\fB\fC--cxxflags\fR
Output C++ preprocessor and compiler flags.
.TP
\fB\fC--config\fR[=\fB\fCapp\fR]
Print default configuration file.
.TP
\fB\fC--makefile\fR[=\fIapp\fP]
Print a simple makefile for an ecpp project.
.TP
\fB\fC--project\fR=\fIapp\fP
Create a simple ecpp project directory.
.TP
\fB\fC--autoproject\fR=\fIapp\fP
Create a autotools based ecpp project.
.TP
\fB\fC--help\fR
Show summary of options.
.TP
\fB\fC--version\fR
Show version of program.
.SH AUTHOR
.PP
tntnet was written by Tommi Mäkitalo 
.MT tommi@tntnet.org
.ME .
.PP
This manual page was written by Kari Pahula 
.MT kaol@debian.org
.ME , for the Debian
project (but may be used by others).
.SH SEE ALSO
.PP
.BR tntnet (8), 
.BR ecppc (1), 
.BR ecppl (1), 
.BR ecppll (1).
.PP
More documentation can be found in /usr/share/doc/tntnet\-doc/.
